### ISSUE TITLE
TypeError: Plain typing.NoReturn is not valid as type argument

### ISSUE THREAD

**Issue by salmaShahid** [pranavvikh03/ResumeRanker_Shared#1]
Your code generate this error

`Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\VisibilityBots\Mylearning\ResumeRanker_Shared-main\venv\lib\site-packages\flask\__main__.py", line 3, in <module>
    main()
  File "E:\VisibilityBots\Mylearning\ResumeRanker_Shared-main\venv\lib\site-packages\flask\cli.py", line 1050, in main
    cli.main()
  File "E:\VisibilityBots\Mylearning\ResumeRanker_Shared-main\venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "E:\VisibilityBots\Mylearning\ResumeRanker_Shared-main\venv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "E:\VisibilityBots\Mylearning\ResumeRanker_Shared-main\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "E:\VisibilityBots\Mylearning\ResumeRanker_Shared-main\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "E:\VisibilityBots\Mylearning\ResumeRanker_Shared-main\venv\lib\site-packages\click\decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "E:\VisibilityBots\Mylearning\ResumeRanker_Shared-main\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "E:\VisibilityBots\Mylearning\ResumeRanker_Shared-main\venv\lib\site-packages\flask\cli.py", line 911, in run_command
    raise e from None
  File "E:\VisibilityBots\Mylearning\ResumeRanker_Shared-main\venv\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "E:\VisibilityBots\Mylearning\ResumeRanker_Shared-main\venv\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "E:\VisibilityBots\Mylearning\ResumeRanker_Shared-main\venv\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "E:\VisibilityBots\Mylearning\ResumeRanker_Shared-main\tester.py", line 7, in <module>
    from resumeExtraction import resumeExtraction
  File "E:\VisibilityBots\Mylearning\ResumeRanker_Shared-main\resumeExtraction.py", line 1, in <module>
    import spacy
  File "E:\VisibilityBots\Mylearning\ResumeRanker_Shared-main\venv\lib\site-packages\spacy\__init__.py", line 6, in <module>
    from .errors import setup_default_warnings
  File "E:\VisibilityBots\Mylearning\ResumeRanker_Shared-main\venv\lib\site-packages\spacy\errors.py", line 2, in <module>
    from .compat import Literal
  File "E:\VisibilityBots\Mylearning\ResumeRanker_Shared-main\venv\lib\site-packages\spacy\compat.py", line 3, in <module>
    from thinc.util import copy_array
  File "E:\VisibilityBots\Mylearning\ResumeRanker_Shared-main\venv\lib\site-packages\thinc\util.py", line 8, in <module>
    from wasabi import table
  File "E:\VisibilityBots\Mylearning\ResumeRanker_Shared-main\venv\lib\site-packages\wasabi\__init__.py", line 2, in <module>
    from .printer import Printer  # noqa
  File "E:\VisibilityBots\Mylearning\ResumeRanker_Shared-main\venv\lib\site-packages\wasabi\printer.py", line 19, in <module>
    class Printer(object):
  File "E:\VisibilityBots\Mylearning\ResumeRanker_Shared-main\venv\lib\site-packages\wasabi\printer.py", line 125, in Printer
    ) -> Union[str, None, NoReturn]:
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\typing.py", line 251, in inner
    return func(*args, **kwds)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\typing.py", line 348, in __getitem__
    parameters = tuple(_type_check(p, msg) for p in parameters)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\typing.py", line 348, in <genexpr>
    parameters = tuple(_type_check(p, msg) for p in parameters)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\typing.py", line 135, in _type_check
    raise TypeError(f"Plain {arg} is not valid as type argument")
TypeError: Plain typing.NoReturn is not valid as type argument`

**Comment by Pathikrish** [comment]
Have you cleared the all errors?
